#!/usr/bin/env bash
# write a Bash script that will display information about subdomains.

get_info() {
    local domain="$1"
    local sub="$2"

    # Construct full domain name
    local subdomain="${sub}.${domain}"

    # Use dig to retrieve info about the subdomain
    local output
    output=$(dig "$subdomain" | grep -A 1 'ANSWER SECTION:')

     # Extract and display the record type and destination from the dig output
    local record_type
    record_type=$( (echo "$output" | awk '{print $4}') | tr -d '\n')
    local destination
    destination=$( (echo "$output" | awk '{print $5}') | tr -d '\n')

    # Display the information
    echo "The subdomain $sub is a $record_type record and points to $destination"
}

domain="$1"

if [ $# -eq 1 ]; then
    # No subdomain specified, so we'll display default subdomains
    get_info "$domain" www
    get_info "$domain" lb-01
    get_info "$domain" web-01
    get_info "$domain" web-02
elif [ $# -gt 2 ]; then
    # Subdomain specified, display information for the specified subdomain
    sub="$2"
    get_info "$domain" "$sub"
fi
