#!/usr/bin/env bash
# A script to install and configure nginx on a server such that its http response contains a custom header

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /hello.html > /dev/null

echo "Ceci n'est pas une page" | sudo tee /my_404.html > /dev/null
host=$(hostname)
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /;
    index hello.html;

    server_name _;

    error_page 404 /my_404.html;

    location /redirect_me {
        return 301 https://github.com/Void-Individual;
    }

    location / {
        add_header X-Served-By "$host";
        try_files \$uri \$uri/ =404;
    }
}
EOF

sudo service nginx restart
