#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive out of it.

sudo mysqldump -u root -p "$1" --all-databases > backup.sql
tar -cfzv "$(date '+%d-%m-%Y').tar.gz" backup.sql
