#!/usr/bin/env bash
# Bash script that displays messages when read some signals

echo $$ > /var/run/script.pid
trap 'echo "I hate the kill command"; rm -rf /var/run/script.pid; exit' SIGTERM
trap 'rm -rf /var/run/script.pid; exit' SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT

while :
do
    echo "To infinity and beyond"
    sleep 2
done
