#!/usr/bin/env bash
# Script to configure nginx to run as an nginx user
sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "s/user .*/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i 's/listen 80 default_server;/listen 80;\n\tlisten *:8080;/' /etc/nginx/sites-available/default
sudo service nginx restart
